sm:
  db:
    host: 192.168.115.129 # 修改为你自己的虚拟机IP地址
    pw: qwaszx134137 # 修改为docker中的MySQL密码
  rd:
    host: 192.168.115.129
    port: 6379
    pw: qwaszx134137
    lettuce:
      pool:
        max-active: 8
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100   #等待连接时间
  cloud:
    nacos:
      server-addr: 192.168.115.129:8848 # nacos地址