server:
  port: 8083  # 端口
spring:
  application:
    name: shopping-mall-wxuser # 服务名
  profiles:
    active: dev # 使用的配置文件
  cloud:
    nacos:
      discovery:
        server-addr: ${sm.cloud.nacos.discovery.server-addr} # nacos地址
  # MySQL配置
  datasource:
    url: jdbc:mysql://${sm.db.host}:3306/sm-wxuser?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${sm.db.pw}
  # Redis配置
  redis:
    host: ${sm.rd.host}
    port: ${sm.rd.port}
    password: ${sm.rd.pw}
    lettuce:
      pool:
        max-active: ${sm.rd.lettuce.pool.max-active} # 最大连接
        max-idle: ${sm.rd.lettuce.pool.max-idle}   # 最大空闲连接
        min-idle: ${sm.rd.lettuce.pool.min-idle}   # 最小空闲连接
        max-wait: ${sm.rd.lettuce.pool.max-wait}   # 等待连接时间

# MybatisPlus配置
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true  # 驼峰映射
    auto-mapping-behavior: full # 完全映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志
  global-config:
    db-config:
      update-strategy: not_null #更新策略:只更新非空字段
      id-type: auto #id自增
  #配置Mapper映射文件
  mapper-locations: classpath:mapper/*.xml

# 日志配置
logging:
  level:
    com.shoppingmall.commodity.mapper: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

# satoken配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# knife4j配置
knife4j:
  enable: true
  openapi:
    title: 微信用户服务接口文档
    description: "信息"
    email: 834302225@qq.com
    concat: LZM
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.shoppingmall.wxuser.controller

#微信小程序配置
weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wx6c6cc5880819450a
  secret: e3811dd51697655847363acb2920e928

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tDMLEYYhBRkzd2HRvZt   # 账号
    accessKeySecret: KFNMNvSglXmXwmjo5QN2HzHUIf7VNY # 密钥
    bucketName: zmproject-web # 空间名

