spring:
  servlet:
    multipart:
      #单个文件最大上传大小
      max-file-size: 100MB
      #单个请求最大上传大小(一次请求可以上传多个文件)
      max-request-size: 100MB

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tDMLEYYhBRkzd2HRvZt   # 账号
    accessKeySecret: KFNMNvSglXmXwmjo5QN2HzHUIf7VNY # 密钥
    bucketName: zmproject-web # 空间名